apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  namespace: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-app
          image: asia.gcr.io/be-nitta-kazuki/streamlit-app:d53d3819be24dfeb0961a417beb3601aee6ee4f0
          ports:
            - containerPort: 8501
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8501
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8501
