name: build and push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup docker buildx
        uses: docker/setup-dockerx-action@v1
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Build and Push docker
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: |
              asia.gcr.io/be-nitta-kazuki/streamlit:${{ github.sha }}
